### ISSUE TITLE
Replay inputs while in session

### ISSUE THREAD

**Issue by JeremyMelton** [mherbold/IRSDKSharper#4]
Hey, really enjoying digging into your sdk. Is is possible to get the inputs during a replay while still in a session?

The scenario is you are driving in a practice session. After a few laps, you leave the car to watch the replay of your laps. From what I'm seeing, I'm still getting the 'live' data rather than what I'm interested in which is the replay data.

Thanks!

**Comment by mherbold** [comment]
​Unfortunately, this is the way iRacing works.  iRacing will continue to broadcast the live data during a live race, even if you are using the replay controls during a live race.  This makes sense because multiple apps could be listening to this data broadcast from iRacing, and if iRacing suddenly started to broadcast replay data instead of live data, this could break many 3rd party apps that depend on the live telemetry being always sent during a live race.

Now that being said, there is a beta/test feature of IRSDKSharper that can help you here - it's called the "Event system" and its basically a data recorder that will record the live data to disk.  The reason for this is because iRacing does not broadcast all of the data back during a replay session - a lot of the data that was originally in the live data is missing in the replay data.  So I built this feature to record live data, so we can get it all back during replay sessions.  There's not much documentation on this feature yet - because it's not officially "out" yet, but its functional and works.  Basically after instantiating IRacingSdk, call EnableEventSystem() and give it any folder name to save the data in.  Then in your OnTelemetryData() callback instead of looking at IRacingSdk.Data (which is always going to be the live data in a live session) you would look at IRacingSdk.EventSystem.Tracks and get your data from there - you'll need to look in the code to see how it works.  But the gist of it is that it basically records data like a multi-track event recorder and you can find data for any frame quite easily.

One caveat - I do exclude many data from the event system that is already broadcast by iRacing during replay sessions (no point in recording something that iRacing already plays back during replay sessions).  I am not sure what you mean by "inputs" but if you are referring to the player's steering wheel angle, gas, and pedal, those are excluded by default.  You can change what is excluded or not by updating the DisallowedTelemetryDataNames hash set.  But be aware that those kinds of inputs change basically every frame and can make your data files huge, so don't go about enabling every telemetry data willy nilly.  :-)

**Comment by JeremyMelton** [comment]
Perfect, I'll take a deeper look into the event system. It sounds exactly like what I'm looking for. 

I am looking for brake/pedal/etc 'inputs' so I appreciate the heads up on data size. Duly noted :) 

Thank you!
